"use client";

import { AlertTriangle, RefreshCw, Sparkles } from "lucide-react";

import { cn } from "@/shared/lib/utils";
import { Button } from "@/shared/ui/button";
import {
  InsightsView,
  LoadingView,
  useInsights,
} from "@/features/ai-analyst";

export function AiAnalystPage() {
  const { state, analyze } = useInsights();
  const busy = state.status === "loading";

  return (
    <div className="flex flex-col gap-6 p-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-xl font-semibold tracking-tight">AI Analyst</h1>
          <p className="text-sm text-muted-foreground">
            An AI read-out of what&apos;s happening across your metrics
          </p>
        </div>
        {state.status === "done" && (
          <Button type="button" variant="outline" size="sm" onClick={analyze} disabled={busy}>
            <RefreshCw className={cn("size-3.5", busy && "animate-spin")} />
            Regenerate
          </Button>
        )}
      </div>

      <div className="rounded-xl border border-border bg-background p-5 shadow-sm sm:p-6">
        {state.status === "idle" && (
          <div className="flex flex-col items-center gap-4 py-10 text-center">
            <span className="flex size-12 items-center justify-center rounded-xl bg-gold text-primary-foreground">
              <Sparkles className="size-6" />
            </span>
            <div className="space-y-1">
              <p className="text-sm font-medium">Explain what&apos;s happening</p>
              <p className="mx-auto max-w-sm text-sm text-muted-foreground">
                Generate an AI summary of your MRR, churn, conversion and recent
                event activity — with highlights, anomalies and next steps.
              </p>
            </div>
            <Button type="button" onClick={analyze} disabled={busy}>
              <Sparkles className="size-4" />
              Generate analysis
            </Button>
          </div>
        )}

        {state.status === "loading" && <LoadingView />}

        {state.status === "error" && (
          <div className="flex flex-col items-center gap-3 py-10 text-center">
            <AlertTriangle className="size-8 text-muted-foreground" />
            <p className="max-w-md text-sm text-muted-foreground">{state.message}</p>
            <Button type="button" variant="outline" size="sm" onClick={analyze}>
              <RefreshCw className="size-3.5" />
              Try again
            </Button>
          </div>
        )}

        {state.status === "done" && <InsightsView insights={state.insights} />}
      </div>

      {state.status === "done" && (
        <p className="text-xs text-muted-foreground">
          Generated by a free AI model via OpenRouter · figures from your live data
        </p>
      )}
    </div>
  );
}
