"use client";

import { useCallback, useEffect, useState } from "react";
import { createPortal } from "react-dom";
import {
  AlertTriangle,
  Lightbulb,
  Loader2,
  RefreshCw,
  Sparkles,
  TrendingUp,
  X,
} from "lucide-react";

import { cn } from "@/shared/lib/utils";
import { Button } from "@/shared/ui/button";
import {
  type AnomalySeverity,
  type InsightSentiment,
  type Insights,
} from "../model/insight";

type State =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "error"; message: string }
  | { status: "done"; insights: Insights };

const sentimentDot: Record<InsightSentiment, string> = {
  positive: "bg-emerald-500",
  neutral: "bg-muted-foreground/50",
  negative: "bg-destructive",
};

const severityStyles: Record<AnomalySeverity, string> = {
  high: "border-destructive/30 bg-destructive/5 text-destructive",
  medium:
    "border-amber-500/30 bg-amber-500/5 text-amber-700 dark:text-amber-400",
  low: "border-border bg-muted/40 text-muted-foreground",
};

/**
 * Кнопка «Explain what's happening» + модалка с AI-разбором метрик.
 * Модалка рендерится через портал в body (как MobileNav) — иначе backdrop-blur
 * topbar'а ограничивает position:fixed рамками шапки.
 */
export function ExplainButton() {
  const [open, setOpen] = useState(false);
  const [mounted, setMounted] = useState(false);
  const [state, setState] = useState<State>({ status: "idle" });

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setMounted(true);
  }, []);

  const analyze = useCallback(async () => {
    setState({ status: "loading" });
    try {
      const res = await fetch("/api/ai/analyze", { method: "POST" });
      const body = await res.json();
      if (!res.ok) {
        setState({
          status: "error",
          message: body?.error ?? "Something went wrong.",
        });
        return;
      }
      setState({ status: "done", insights: body.insights as Insights });
    } catch {
      setState({ status: "error", message: "Network error. Please try again." });
    }
  }, []);

  const openPanel = useCallback(() => {
    setOpen(true);
    // Анализируем при открытии, но не перегенерируем уже готовый результат.
    if (state.status !== "done") void analyze();
  }, [analyze, state.status]);

  const close = useCallback(() => setOpen(false), []);

  // Escape закрывает модалку.
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open]);

  const modal = (
    <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto p-4 sm:items-center sm:p-6">
      <button
        type="button"
        aria-label="Close"
        className="fixed inset-0 bg-black/60 animate-in fade-in-0 duration-200"
        onClick={close}
      />

      <div
        role="dialog"
        aria-modal="true"
        aria-label="AI analysis"
        className="relative z-10 my-auto flex w-full max-w-2xl flex-col rounded-xl border border-border bg-background shadow-2xl animate-in fade-in-0 zoom-in-95 duration-200"
      >
        {/* Шапка */}
        <div className="flex items-center gap-2.5 border-b border-border px-5 py-3.5">
          <span className="flex size-7 shrink-0 items-center justify-center rounded-lg bg-gold text-primary-foreground">
            <Sparkles className="size-4" />
          </span>
          <div className="min-w-0 flex-1">
            <h2 className="text-sm font-semibold">AI analyst</h2>
            <p className="truncate text-xs text-muted-foreground">
              What&apos;s happening in your workspace
            </p>
          </div>
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            aria-label="Close"
            onClick={close}
          >
            <X className="size-4" />
          </Button>
        </div>

        {/* Тело */}
        <div className="max-h-[70vh] overflow-y-auto px-5 py-4">
          {state.status === "loading" && <LoadingView />}

          {state.status === "error" && (
            <div className="flex flex-col items-center gap-3 py-8 text-center">
              <AlertTriangle className="size-8 text-muted-foreground" />
              <p className="max-w-sm text-sm text-muted-foreground">
                {state.message}
              </p>
            </div>
          )}

          {state.status === "done" && <InsightsView insights={state.insights} />}
        </div>

        {/* Подвал */}
        <div className="flex items-center justify-between gap-3 border-t border-border px-5 py-3">
          <p className="text-xs text-muted-foreground">
            Generated by Claude · figures from your live data
          </p>
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={analyze}
            disabled={state.status === "loading"}
          >
            <RefreshCw
              className={cn("size-3.5", state.status === "loading" && "animate-spin")}
            />
            Regenerate
          </Button>
        </div>
      </div>
    </div>
  );

  return (
    <>
      <Button
        type="button"
        variant="outline"
        size="sm"
        className="shrink-0"
        onClick={openPanel}
      >
        <Sparkles className="size-4" />
        <span className="hidden sm:inline">Explain what&apos;s happening</span>
      </Button>

      {mounted && open ? createPortal(modal, document.body) : null}
    </>
  );
}

function LoadingView() {
  return (
    <div className="space-y-4 py-2">
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Loader2 className="size-4 animate-spin" />
        Analyzing your metrics…
      </div>
      <div className="space-y-2">
        <div className="h-4 w-3/4 animate-pulse rounded bg-muted" />
        <div className="h-3 w-full animate-pulse rounded bg-muted" />
        <div className="h-3 w-5/6 animate-pulse rounded bg-muted" />
      </div>
      <div className="grid gap-2 sm:grid-cols-2">
        {Array.from({ length: 4 }).map((_, i) => (
          <div key={i} className="h-14 animate-pulse rounded-lg bg-muted" />
        ))}
      </div>
    </div>
  );
}

function InsightsView({ insights }: { insights: Insights }) {
  return (
    <div className="space-y-6">
      {/* Заголовок + сводка */}
      <div className="space-y-2">
        <p className="text-base leading-snug font-semibold">{insights.headline}</p>
        <p className="text-sm leading-relaxed text-muted-foreground">
          {insights.summary}
        </p>
      </div>

      {/* Ключевые наблюдения */}
      {insights.highlights.length > 0 && (
        <Section icon={TrendingUp} title="Highlights">
          <div className="grid gap-2 sm:grid-cols-2">
            {insights.highlights.map((h, i) => (
              <div
                key={i}
                className="rounded-lg border border-border bg-muted/30 p-3"
              >
                <div className="flex items-center gap-2">
                  <span
                    className={cn(
                      "size-1.5 shrink-0 rounded-full",
                      sentimentDot[h.sentiment]
                    )}
                  />
                  <span className="text-xs font-medium">{h.label}</span>
                </div>
                <p className="mt-1 text-sm text-muted-foreground">{h.detail}</p>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Аномалии */}
      {insights.anomalies.length > 0 && (
        <Section icon={AlertTriangle} title="Anomalies">
          <div className="space-y-2">
            {insights.anomalies.map((a, i) => (
              <div
                key={i}
                className={cn("rounded-lg border p-3", severityStyles[a.severity])}
              >
                <div className="flex items-center justify-between gap-2">
                  <span className="text-sm font-medium">{a.title}</span>
                  <span className="text-[10px] font-semibold uppercase tracking-wide opacity-70">
                    {a.severity}
                  </span>
                </div>
                <p className="mt-1 text-sm opacity-90">{a.detail}</p>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Рекомендации */}
      {insights.recommendations.length > 0 && (
        <Section icon={Lightbulb} title="Recommendations">
          <ul className="space-y-2">
            {insights.recommendations.map((r, i) => (
              <li key={i} className="flex gap-2.5 text-sm">
                <span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-gold/15 text-xs font-semibold text-primary">
                  {i + 1}
                </span>
                <span className="text-muted-foreground">{r}</span>
              </li>
            ))}
          </ul>
        </Section>
      )}
    </div>
  );
}

function Section({
  icon: Icon,
  title,
  children,
}: {
  icon: typeof TrendingUp;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-2.5">
      <h3 className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        <Icon className="size-3.5" />
        {title}
      </h3>
      {children}
    </section>
  );
}
